// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockApp1.API.MyData;

namespace StockApp1.API.Migrations
{
    [DbContext(typeof(StockDataContext))]
    [Migration("20180709165419_Added Userlogin model")]
    partial class AddedUserloginmodel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("StockApp.MyModels.Userlogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PwdHash");

                    b.Property<byte[]>("PwdSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Userlogins");
                });

            modelBuilder.Entity("StockApp1.API.MyModels.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Close");

                    b.Property<string>("Name");

                    b.Property<string>("Symbol");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
